package com.airlinemanagementsystem.payment.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PaymentVerificationRequest {

    // The Order ID generated in the 'initiate' step
    private String razorpayOrderId;

    // The Payment ID generated by Razorpay after user pays
    private String razorpayPaymentId;

    // The cryptographic signature to prove the payment is authentic
    private String razorpaySignature;
}
