server:
  port: 8082

spring:
  application:
    name: booking-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # This URL must match the 'iss' field in the token exactly
          issuer-uri: http://localhost:8180/realms/airline-realm
          # URL to fetch the Public Key for signature validation
          jwk-set-uri: http://airline-keycloak:8080/realms/airline-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/booking_service_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: booking-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: true
            type:
              mapping: >
                com.airlinemanagementsystem.payment.dto.PaymentEvent:
                com.airlinemanagementsystem.booking.dto.PaymentEventDto

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
